pipeline {
  agent any
  stages {
    stage('Build ') {
      steps {
        sh '''pwd
date'''
      }
    }

    stage('Test') {
      parallel {
        stage('Test') {
          steps {
            echo 'testtest step'
          }
        }

        stage('Test Par') {
          steps {
            echo 'Test par'
          }
        }

      }
    }

    stage('Deploy') {
      steps {
        echo 'deploy'
        sleep 13
      }
    }

  }
}
